Address = "0x0"
RPC = "https://builder-relay.48.club"
Website = "https://www.48.club/validation-node"
TelegramGroup = "https://t.me/+nhIQNj5G3lY2M2U9"
Description = "Join the dedicated Telegram Group for integrating with 48Club partner validators"
Contact = "validators@48.club"
