Address = "0x48B2665E5E9a343409199D70F7495c8aB660BB48"
RPC = "https://puissant-builder.48.club"
Website = "https://www.48.club"
Description = "Puissant means powerful in French."
Contact = "puissant@48.club"