Address = "0x488e37fcB2024A5B2F4342c7dE636f0825dE6448"
RPC = "https://x.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We provide an audited builder solution that ensures each block, transaction, and bundle is scrutinized by authoritative security agencies. Utilizing multiple strategies and advanced algorithms, we aim to build the most valuable and secure blocks. Visit our website for more information!"
Contact = "support@blockrazor.io"