Address = "0x50061047B9c7150f0Dc105f79588D1B07D2be250"
RPC = "https://tokyo.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"