Address = "0x539E24781f616F0d912B60813aB75B7b80b75C53"
RPC = "https://nyc.builder.blockrazor.io"
Website = "https://www.blockrazor.io"
Description = "We build this neutral builder with multiple strategies and algorithms to make most valuable block. Check our website for more info!"
Contact = "support@blockrazor.io"